# Generated by Django 4.1 on 2022-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
    ]
